resume/urls.py
from django.conf.urls import url
from django.contrib import admin

from resume.views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', index, name='index'),
]

resume/models.py
from django.db import models


class ResumeSection(models.Model):
    title = models.CharField(max_length=200)
    icon_name = models.CharField(max_length=20, default='book')
    inline = models.BooleanField(default=False);

    def __str__(self):
        return self.title


class ResumeSectionItem(models.Model):
    section = models.ForeignKey(ResumeSection, on_delete=models.CASCADE)
    first = models.BooleanField('first', blank=True, default=False)
    prefix = models.CharField('prefix', blank=True, null=True, max_length=50)
    start_date = models.DateField('start', blank=True, null=True)
    end_date = models.DateField('end', blank=True, null=True)
    header = models.CharField(max_length=100, default='HEADER')
    description = models.CharField('description', blank=True, null=True, max_length=500)

    def __str__(self):
        return self.header


class AboutMeSection(models.Model):
    title = models.CharField(max_length=100)
    body = models.CharField(max_length=5000)

    def __str__(self):
        return self.title + ": " + self.body


class Project(models.Model):
    name = models.CharField(blank=False, max_length=50)
    category = models.CharField(blank=False, max_length=200)
    img_name = models.CharField(blank=False, max_length=20)
    link = models.CharField(blank=True, max_length=2000)

    def __str__(self):
        return self.name

resume/views.py
from django.shortcuts import render

from .models import ResumeSection, AboutMeSection, Project


def index(request):
    resume_list = ResumeSection.objects.order_by('id')
    about_me = AboutMeSection.objects.order_by()
    projects = Project.objects.order_by()

    context = {
        'resume_list': resume_list,
        'about_me': about_me,
        'resume_item_offset': len(resume_list) if len(resume_list) < 3 else 3,
        'projects': projects,
    }
    return render(request, 'index.html', context)

resume/templates/base.html
<!--DOCTYPE html -->
{% load static %}

<html>
    <head>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{% block title %}Ben Richards{% endblock %}</title>

        <!-- favicon -->
        <link rel="shortcut icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">
        <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/x-icon">

        <!-- Bootstrap Core CSS -->
        <link  rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}"/>

        <!-- Custom Fonts -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.css' %}"/>
        <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'/>
        <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'/>

        <!-- Plugin CSS -->
        <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet"/>

        <!-- Theme CSS -->
        <link href="{% static 'css/creative.css' %}" rel="stylesheet"/>

        <!-- Ben's CSS -->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
            <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
            <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->

    </head>

    <body id="page-top">

        <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <!-- Brand and toggle get grouped for better mobile display -->
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                    </button>
                    <a class="navbar-brand page-scroll" href="{% url 'index' %}">Ben Richards</a>
                </div>

                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a class="page-scroll"
                               href="{% if request.get_full_path == '/' %}
                                        #page-top
                                     {% else %}
                                        {% url 'index' %}
                                     {% endif %}">Home</a>
                        </li>
                        {% block navbar %}
                        {% endblock navbar %}
                    </ul>
                </div>
                <!-- /.navbar-collapse -->
            </div>
            <!-- /.container-fluid -->
        </nav>

        <header>
            <div class="header-content">
                <div class="header-content-inner">
                    <h1 id="homeHeading">Ben Richards</h1>
                    <div id="profile-pic"></div>
                    <hr>
                    <p><em>"Innovation distinguishes between a leader and follower." - Steve Jobs</em></p>
                    <a href="{% if about_me %}#about{% else %}#resume-section{% endif %}" class="btn btn-primary btn-xl page-scroll">Click or Scroll for More</a>
                </div>
            </div>
        </header>

        <div class="page-content">
            {% block content %}
            {% endblock %}
        </div>

        <footer id="copyright">
            <div class="container">
                    <div class="text-center">
                        <h6>Copyright &copy; Ben Richards 2016</h6>
                    </div>
            </div>
        </footer>

        <!-- jQuery -->
        <script src="{% static 'javascript/jquery.min.js' %}"></script>

        <!-- Bootstrap Core JavaScript -->
        <script src="{% static 'javascript/bootstrap.min.js' %}"></script>

        <!-- Plugin JavaScript -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>
        <script src="{% static 'javascript/scrollreveal.min.js' %}"></script>
        <script src="{% static 'javascript/jquery.magnific-popup.min.js' %}"></script>

        <!-- Theme JavaScript -->
        <script src="{% static 'javascript/creative.min.js' %}"></script>

    </body>
</html>

resume/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block navbar %}
    {% if about_me %}
        <li><a class="page-scroll" href="#about">About Me</a></li>
    {% endif %}
        <li><a class="page-scroll" href="#resume-section">Resume</a></li>
    {% if projects %}
        <li><a class="page-scroll" href="#portfolio">Companies</a></li>
    {% endif %}
    <li>
        <a class="page-scroll" href="#contact">Contact</a>
    </li>
{% endblock navbar %}

{% block content %}
    {% if about_me %}
        <section class="bg-primary" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-lg-offset-2 text-center">
                        <h2 class="section-heading">About Me</h2>
                        <hr class="light">
                        {% for section in about_me %}
                            <p class="text-faded">{{ section.body }}</p>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </section>
    {% endif %}

    {% if resume_list %}
        <section id="resume-section" class="small-padding">
            <div class="container">
                <div class="row">
                    {% for section in resume_list %}
                        <div class="col-lg-4">
                                <i class="fa fa-5x fa-{{ section.icon_name }} text-primary sr-icons"></i>
                                <h3 class="resume-section-title">{{ section }}</h3>
                                {% if section.inline %}
                                    <ul class="list-inline">
                                        {% for item in section.resumesectionitem_set.all %}
                                            <li class="text-muted item-header">
                                                {% if not item.first %}&bull;&emsp;&emsp;{% endif %}{{ item.header }}
                                                {% if item.start_date or item.prefix %}
                                                    <em>&emsp;{% if item.prefix %}{{item.prefix}} {% endif %}{{item.start_date|date:"Y"}}{% if item.end_date %}-{{item.end_date|date:"Y"}}{% endif %}</em>
                                                {% endif %}
                                            </li>
                                            {% if item.description %}
                                                <li class="item-description">
                                                    {{ item.description }}
                                                </li>
                                            {% endif %}
                                        {% endfor %}
                                    </ul>
                                {% else %}
                                    {% for item in section.resumesectionitem_set.all %}
                                        <p class="text-muted item-header">
                                            <strong>{{ item.header }}</strong>
                                            {% if item.start_date or item.prefix %}
                                                {% if item.prefix %}{{item.prefix}} {% endif %}{{item.start_date|date:"Y"}}{% if item.end_date %}-{{item.end_date|date:"Y"}}{% endif %}
                                            {% endif %}
                                        </p>
                                        {% if item.description %}
                                            <p class="item-description">
                                                {{ item.description }}
                                            </p>
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    {% endif %}

    <section class="no-padding" id="portfolio">
        <div class="container-fluid">
            <div class="row no-gutter popup-gallery">
                {% for project in projects %}
                <div class="col-lg-4 col-sm-6">
                    <a href="{% static 'images/portfolio/fullsize/'|add:project.img_name|add:'.jpg' %}" class="portfolio-box">
                        <img src="{% static 'images/portfolio/thumbnails/'|add:project.img_name|add:'.jpg' %}" class="img-responsive" alt="">
                        <div class="portfolio-box-caption">
                            <div class="portfolio-box-caption-content">
                                <div class="project-category text-faded">
                                    {{ project.category }}
                                </div>
                                <div class="project-name">
                                    {{ project.name }}
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>

    <section class="bg-primary" id="contact">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <h2 class="section-heading">Contact Me</h2>
                    <hr class="light">
                    <p>Get in touch with me through any of the links below</p>
                </div>
                <div class="col-lg-2 col-lg-offset-3 text-center">
                    <i class="fa fa-github fa-3x sr-contact"></i>
                    <p></p>
                    <p><a href="https://www.github.com/blrichards" class="text-faded" id="facebook">github</a></p>
                </div>
                <div class="col-lg-2 text-center">
                    <i class="fa fa-envelope-o fa-3x sr-contact"></i>
                    <p><a href="mailto:ben@benrichards.xyz" class="text-faded no-decoration">email</a></p>
                </div>
                <div class="col-lg-2 text-center">
                    <i class="fa fa-linkedin fa-3x sr-contact"></i>
                    <p></p>
                    <p><a href="https://www.linkedin.com/in/ben-richards-809a9793" class="text-faded no-decoration">linkedin</a></p>
                </div>
                <div class="col-lg-8 col-lg-offset-2 text-center">
                    <hr class="light">
                    <p><em>code for this website can be found on my <code><a href="https://github.com/blrichards/Resume-Site">github</a></code></em></p>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}